name: Lint JS

on: [push, pull_request]

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies and build
        run: npm ci

      - run: npm run lint:js
