name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      REPORT_GAS: true
      COINMARKETCAP_API_KEY: ${{secrets.COINMARKETCAP_API_KEY}}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Prepare env
        run: cp .env.example .env

      - name: Install dependencies and build
        run: npm ci

      - name: Run tests
        run: make test

      - name: Coverage
        run: make coverage

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
            artifacts/contracts/Contract.sol/Contract.json
            artifacts/contracts/ContractFactory.sol/ContractFactory.json
