name: Tests

on: ["push"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: prepare env
        run: cp .env.example .env

      - name: install dependencies
        run: npm install

      - name: run tests
        run: make test
